# Generated by Django 5.1.3 on 2024-11-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('colore_divisa', models.CharField(max_length=50)),
                ('num_max_giocatori', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrizione', models.TextField()),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField()),
                ('squadre', models.ManyToManyField(to='serie_zeta.squadra')),
            ],
        ),
    ]
