# Generated by Django 5.1.3 on 2024-11-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serie_zeta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('jersey_color', models.CharField(max_length=50)),
                ('players_num_max', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='torneo',
            name='squadre',
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('teams', models.ManyToManyField(to='serie_zeta.team')),
            ],
        ),
        migrations.DeleteModel(
            name='Squadra',
        ),
        migrations.DeleteModel(
            name='Torneo',
        ),
    ]
