# Generated by Django 5.1.3 on 2024-11-20 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serie_zeta', '0002_team_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentparticipation',
            name='team',
            field=models.ForeignKey(limit_choices_to={'is_deleted': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='serie_zeta.team'),
        ),
    ]
